services:
  ollama:
    container_name: ollama
    image: ollama/ollama
    ports:
      - ${OLLAMA}:11434
    volumes:
      - ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:cuda
    depends_on:
      - ollama
    ports:
      - ${OPENWEBUI}:8080
    environment:
      - OLLAMA_BASE_URL=http://ollama:${OLLAMA}
    volumes:
      - openwebui:/app/backend/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

volumes:
  openwebui:
  ollama: