services:
    # Warnning GPU is required
  comfyui:
    image: saladtechnologies/comfyui:comfy0.3.61-api1.9.2-torch2.8.0-cuda12.8-flux1-schnell-fp8
    container_name: comfyui
    ports:
      - ${COMFYUI}:8188
    volumes:
      - comfy_models:/opt/ComfyUI/models
      - comfy_output:/opt/ComfyUI/output
    environment:
      - DISABLE_WORKFLOWS=true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
volumes:
  comfy_models:
  comfy_output: